controller_joint_names: ['', 'RockerIzq', 'Llanta3', 'BogieIzq', 'Llanta1', 'Llanta2', 'RockerDer', 'Llanta6', 'BogieDer', 'Llanta4', 'Llanta5', 'Pivote_', 'Union1', 'Caja_Pivote_1', 'Union2', 'Caja_Pivote_2', ]
